<svg class="curvePink down" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" viewBox="0 0 500 150" preserveAspectRatio="none">
    <path d="M0,50 C80,150 180,20 220,50" style="
    fill: none;
    stroke-width: 3;
"></path>
    <path d="M280,50 C360,20 460,150 500,0" style="
    fill: none;
    stroke-width: 3;
"></path>
</svg>
<?php
/**
 * Created by PhpStorm.
 * User: andrea.becchio
 * Date: 19/12/2015
 * Time: 23:46
 */

$prodlist = $this->getLayout()->getBlock('hp_product_list')->toHtml();

echo $prodlist;
?>

