<?php
/**
 * Created by PhpStorm.
 * User: andrea.becchio
 * Date: 19/12/2015
 * Time: 23:30
 */

$slider = $this->getLayout()->getBlock('hp_slider')->toHtml();
?>
<div class="slideshow-container">

    <?php echo $slider;?>
<!--
    <div class="slideshow-pager" style="display:none">&nbsp;</div>
    <span class="slideshow-prev">&nbsp;</span> <span class="slideshow-next">&nbsp;</span>
    -->
</div>


